<a href="https://colab.research.google.com/github/JAEILJEON/JAEIL_DATA/blob/main/210627_Numpy_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 구글드라이브 연동



In [ ]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# 구글 드라이브 파일 확인
!ls '/gdrive/My Drive/temp/'

# 반복되는 드라이브 경로 변수화
drive_path = '/gdrive/My Drive/temp/'

Mounted at /gdrive
 매수종목1.txt		   little-char.png	   seoul_map.html
 매수종목2.txt		   ml_class.png		   sonar.csv
 adult.data		   pca_1.png		   stock-data.csv
 auto-mpg.csv		   pca_2.png		  'stock price.xlsx'
 bmi_500.csv		   pca_3.png		  'stock valuation.xlsx'
 citibike.csv		   Picture1.png		   test.db.db
 매수종목.csv		   population_number.csv   test.txt
 data_mine.csv		   ram_price.csv	   ThoraricSurgery.csv
 data_population.csv	   ratings_small.txt	   titanic.xls
 data_studentlist_en.csv   ratings_test.txt	   tmdb_5000_credits.csv
 demo.docx		   ratings_train.txt	   tmdb_5000_movies.csv
 diabetes.csv		   sample1.pdf		   Traffic_Accident_2017.csv
 example.docx		   sample2.pdf		   train.csv
 height_weight.txt	   sample.docx		   user_id_mean.csv
 HelloWorld.xlsx	   sample_merge.pdf	   wine.csv
 house_price.csv	   sample.xlsx		   주가데이터.xlsx
 lenna.png		   score.csv		   남북한발전전력량.xlsx


### 파이썬 머신러닝을 위한 모듈(라이브러리)


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

## Numpy 기초


In [ ]:
# Numpy 모듈(라이브러리)를 import하고 np 라는 이름으로 부르는 것이 관례
# 넘파이 왕이 되겠다. 진짜 완벽히 체화시키자. 매일 복습하고!
import numpy as np


In [ ]:
#대부분 .__version__ 하면 버전이 나온다. 대부분! tensorflow도 마찬가지!
#라이브러리 버전을 넣고 검색하면 훨씬 편함
np.__version__

'1.19.5'

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.


In [ ]:
#np.ndarray() 를 쓰는 법
#ndarray는 n dimension 이잖아? 이건 n차원 문제임. n차원. 방향성. 만약 2차원이면 방향이 2개. 방향성이 2개임! 랭크로 이야기하기도 하고. 이거 깨봉수학에서 아침에 했잖아~
#난 그래서 np.array 할 때 처음에 리스트 형태로 넣어주는 이유가 차원 형성 때문인 것 같음. 

list = [1,2,3]
array1 = np.array(list)
print( type(array1), array1.shape )
#type은 ndarray로 나옴. 
#3개짜리 요소가 들어있는 1차원 배열이다. 이게 shape 내가 아는 shape은 차원(축) 별로 포함된 원소 개수임. 지금은 호 3개.

array2 = np.array( [[1,2,3],
                    [4,5,6]] ) # 리스트 안에 리스트. 이게 2차원 배열. 2차원 배열은 층 호잖아? 이렇게 하면 눈으로 볼 때 훨씬 편함. 2층에 3호씩. 
print( array2, array2.shape  ) #array2.shape하니까 (2,3) 이렇게 나오잖아. 2층에 3호씩이니까 ! 

array3 = np.array( [[1,2,3]] )

print( array3 )
print( array3.shape ) #내 예상. (1,3). 1층에 3호니까~ 이게 1행 3열인 거지~ 모양, 크기. 이렇게 하고 tuple 형태로 출력이 됨. 
                      #shape은 차원별로 몇개씩 원소가 들어있는지 알게 되니까~ 

<class 'numpy.ndarray'> (3,)
[[1 2 3]
 [4 5 6]] (2, 3)
(1, 3)


In [ ]:
#.ndim을 활용해서 몇 차원인지 확인하기
array1.ndim

(3, 6, 3)

In [ ]:
# 원소의 총 개수 구하기
array1.size, array2.size, array3.size #size가 총 요소 개수. shape가 차원별 요소 개수.

ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [ ]:
#np.ndarray() 를 쓰는 법

list = [1,2,3]
array1 = np.array(list)
print( type(array1), array1.shape )
#type은 ndarray로 나옴. 
#3개짜리 요소가 들어있는 1차원 배열이다. 이게 shape 내가 아는 shape은 차원(축) 별로 포함된 원소 개수임. 지금은 호 3개.

array2 = np.array( [[1,2,3],
                    [4,5,6]] ) # 리스트 안에 리스트. 이게 2차원 배열. 2차원 배열은 층 호잖아? 이렇게 하면 눈으로 볼 때 훨씬 편함. 2층에 3호씩. 
print( array2, array2.shape  ) #array2.shape하니까 (2,3) 이렇게 나오잖아. 2층에 3호씩이니까 ! 

array3 = np.array( [[1,2,3]] )

print( array3 )
print( array3.shape ) #내 예상. (1,3). 1층에 3호니까~ 이게 1행 3열인 거지~ 모양, 크기. 이렇게 하고 tuple 형태로 출력이 됨. 
                      #shape은 차원별로 몇개씩 원소가 들어있는지 알게 되니까~ 

numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


In [ ]:
# 8 16 32 64 이건 비트 이야기임. 거의 다 64임.
# uint는 unsigned int 임. 숫자를 더 많이 쓸 수 있다.
# 파이썬에서 사용하는 자료형은 거의 다 된다. 하지만 오브젝트가 들어가면 계산은 어려워짐~

list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
array1.dtype #dtype은 ndarray의 속성임. 64비트

<class 'list'>


dtype('int64')

In [ ]:
#다른 타입 혼용 #가장 크게 호환할 수 있는 거로 다 바뀜.
import numpy as np

list2 = [1,2, 'test']
print( type(list2) )

array2 = np.array(list2)  #내부 코드를 저장할 때 str은 자체 구조를 만듦. 아스키 구조. 유니코드는 유니코드로 바뀌고, str은 아스키 코드로 바뀐다. 그 차이임.
array2.dtype, array2    #np.array로 바꾸니까, 전부다 str로 바뀜. 문자는 int가 될 수 없지만 숫자는 str이 될 수 있어서 다 포함 가능한 str로 바뀐 것

<class 'list'>


(dtype('<U21'), array(['1', '2', 'test'], dtype='<U21'))

In [ ]:
list3 = [1, 2, 3.1]
array3 = np.array(list3)
array3.dtype

print( 'array3',array3.dtype, array3 )  #데이터 변형시 전체를 포함할 수 있는 형태로 바꿔버림. 그래서 여기선 float으로 바뀐 것.

array3 float64 [1.  2.  3.1]


- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
#큰 데이터 타입이라는 건 가장 포괄적인 데이터 타입으로 변환된다는 것. 
#타입을 바꿀 수 없나? 
#타입 변경

array_int = np.array( [1,2,3] )
print(array_int, array_int.dtype)
#이거 중요함. 
array_float = array_int.astype('float64')   # astype()정수형이었던 것을 전부 실수형으로 바꿔주는 것. 가장 많이 쓰이는 속성 중 하나. 이걸 정수형으로 바꾼다면? .astype('int64') 이렇게 바꿔주면 됨.
print( array_float.dtype )

[1 2 3] int64
float64


In [ ]:
#생성할 때부터 아예 타입을 지정하여 생성하고 싶다면?

array_int = np.array( [1.1, 2.1, 3.1], dtype=np.int64 ) #아예 실수형으로 입력 받아보자 처음부터. 이걸 처음부터 int형으로 지정해주고 싶다면?

print(array_int)
print(array_int.dtype)

[1 2 3]
int64


#### Numpy 예제 01
Numpy를 이용해 다음과 같은 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수을 확인해보자 
```
array([[[1,2],
        [3,4]],
        
       [[5,6],
        [7,8]]])
```
```
배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8
```


In [ ]:
#예제 내가 푼 것

array_3d = np.array( [[[1,2],
                       [3,4]],
                      
                      [[5,6],
                       [7,8]]] )

print(array_3d)
print( '배열의 크기' ,array_3d.shape )
print( array_3d.ndim )
print( array_3d.size )


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
배열의 크기 (2, 2, 2)
3
8


### ndarray 생성

In [ ]:
#여기서 아마 np.arange() 쓸 것 같은데? 
#ndarray() 생성.
#연속값으로 생성. 
seq_array = np.arange(10) #range()하고 사용법은 거의 비슷함.
seq_array, seq_array.dtype, seq_array.shape #대충 눈으로만 확인하고 싶을 때 print() 안하고 그냥할 때

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'), (10,))

In [ ]:
#0으로 가득찬 녀석을 만들고 싶을 때. 초기화라고 하기도 함. 
#np.zeros() 0으로 다 채운 녀석을 만들 수 있음. 모양만 넣어주면 돼. 2x2인지, 3x3인지 뭐 행열 지정해주면 돼
#쉼표 마침표. 마침표는 내부 속성 사용할 때 사용함. 단순 나열은 쉼표!

zero_array = np.zeros( (3,2), dtype=np.int64 )
zero_array, zero_array.shape    #모양도 아주 깔끔하게 만들어주네 ㅎㅎ

(array([[0, 0],
        [0, 0],
        [0, 0]]), (3, 2))

In [ ]:
#0말고 1로 채울 수도 있음
#np.ones()를 하면 1로 채워진 녀석을 만들 수 있다.

one_array = np.ones( (3,4), dtype=np.float64 ) #이건 float형으로 넣어봐야지
one_array, one_array.shape

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), (3, 4))

In [ ]:
#특정값으로 초기화. 별로 많이 쓰진 않음.
import numpy as np

full_array = np.full( (5,5), 7 )   #난 5x5 배열을 7로 가득 채우겠다!

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
#랜덤 초기화

np.random.seed(10) #seed 값을 넣는데, 10을 하면 항상 10번째 랜덤수부터 제공되는 것임. 보통 초기화 시킬 때, 넘파이 랜덤과 텐서플로우 랜덤 초기화 둘 다 씀.

In [ ]:
#random값으로 초기화 시키기! 
#넘파이 랜덤으로 보통 초기화시킴. 랜덤이 실행되는 순서대로 같은 값이 나와야 함.
#랜덤으로 초기화 시켜야 매번 같은 값이 나오는 걸 확인할 수 있음.

#랜덤은 가상 데이터 만들어서 테스트 시킬 때도 씀.

a = np.random.randint( 2, 10, size=(2,3) ) #2~10 사이 수로, 2행 3열로.
print( a, a.dtype )

[[9 4 8]
 [5 8 7]] int64


#### Numpy 예제 02
1,2,3,....,50 이 담긴 배열을 생성하시오.

In [ ]:
seq_array = np.arange(1, 51).reshape(5,10) #.reshape()로 차원 축도 막 생성시킬 수 있네. #이건 5행 10열이니까 1,11,21,31,41 행  / 1~10 열
seq_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### ndarray 차원과 크기 변경

In [ ]:
#모양 바꾸기
#.reshape() 쓸 것 같은데?

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

#reshape에서 많이 쓰는 경우 중 하나가 -1 쓰는 것. -1을 쓰면 그 부분에 맞춰서 알아서 써줌.
#자동으로 호환가능하게.

array4 = array1.reshape(-1, 2)
print(array4)

array5 = array1.reshape(5, -1)
print(array4)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#8개짜리 만들어서 3차원으로 만들어보기

array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print( array3d.tolist() )  #tolist는 뭐지? tolist 활용해서 리스트로 뽑기.

#이걸 8,1이 되도록 2차원으로 바꾼다면 어떻게 바꿀까?
array5 = array3d.reshape(-1,1)
print(array5)

#얘도 이렇게 가능
print(array1.reshape(-1,1)) #배열만 같으면 연산 가능임.

#넘파이는 사기적이다. 프로그래머스에서도 이거 사용 가능임ㅋㅋ

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [ ]:
#인덱싱은 서치하는 것. for 문이나 뭐 이런 거 안쓰고도 바로 접근 가능한 것.
#인덱싱은 데이터 추출. 기존과 일치함.
#팬시와 불린은 중간중간 조건에 맞으면 갖고 올 수 있음.

array = np.arange(1,10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#인덱스 사용하는 부분은 리스트하고 똑같음
array[-1], array[-2], array[2], array[0]


(9, 8, 3, 1)

In [ ]:
#데이터가 수정하고 싶을 때
array[0] = 10 #0번 자리를 10으로 바꾸고 싶을 때. 리스트 사용하는 것과 동일하게 직접 접근해서 바꿀 수 있음.
print(array)

array[0] = 1
print(array)

[10  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원 인덱싱

array1d = np.arange(1,10)     #굳이 이렇게 2번 나눠서 안하고  np.arange(1,10).reshape(3,3) 이렇게 해도 됨.
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0][1]) #0층에 1호. 그럼 [1,2,3] 에서 1번 위치니까 2반환. 근데 이렇게 하면 비효율적이니까
print(array2d[0,1]) #바로 윗코드하고 동일한데, 이게 더 효율적임.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
print(array2d[0,1]) #이걸 하면 2가 나오지. 0층, 1호. 0행 1열. 
print(array2d[1,0]) #이걸 하면 4가 나오지. 1층 0호 1행 0열
print(array2d[2,2]) #이걸 하면 9가 나오지. 2층 2호 2행 2열

#3차원도 2차원으로 변형시켜서 하면 되니까 3차원일 땐 하지마 ㅜㅠ 2차원으로 변형시켜서 해


2


슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



In [ ]:
#얘도 이상 이하야. 슬라이싱 할 때도 이상 이하임. arange()도 이상 이하고.

#1차원 슬라이싱
arr = np.arange(1,10)

print( arr )
print( arr[0:3] )
print( arr[:3] )
print( arr[3:] )

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


In [ ]:
#2차원 슬라이싱
#이건 진짜 중요하니까 잊지마. numpy는 진짜 많이 쓴다!!

arr = np.arange(1,10).reshape(3,-1) #바로 이렇게 한 줄로 만들어주는 것.
print(arr)

#[4,5,6]만 가져오고 싶다면 어떻게 할까?
#print(arr[1,:])
#print(arr[1:2,:])

#만약에 [ 1, 2 ]
      # [ 4, 5 ] 이렇게 가져오고 싶다면 어떻게 할까?
#print(arr[ 0:2 , 0:2 ])  #앞에가 0번째 축, 뒤에가 1번째 축임. 층, 호 라는 이야기. 층을 몇번까지 쓸 건지 정한 다음에, 호를 몇번까지 쓸 건지 결정.

#[[4,5,6],
# [7,8,9]] 이렇게 가져오고 싶다면?
#print(arr[1: , : ])

#[[5],
# [8]] 이렇게 가져오고 싶다면?
#print(arr[ 1: , 1:2 ])

#[[2,3],
# [5,6]] 이렇게 가져오고 싶다면?
print(arr[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


팬시 인덱싱

In [ ]:
#1차원 팬시 인덱싱
import numpy as np

arr = np.arange(1,10)
print(arr)
print(arr[[3,4,7]]) #인덱싱을 목록으로 제공한 것. 인덱스 안에 리스트나 ndarray로 넣어주는 것. 임의의 위치에서 값을 가져오고 싶을 때 사용하는 게 팬시 인덱싱과 불린 인덱싱임.
                    #원래 인덱스는 숫자 하나로 들어가는데, 팬시 인덱싱에서는 여러 인덱스를 넣으니까 값을 리스트로 받음.
                    #뭐 그리 어려운 개념은 아님. 1차원이잖아 아직?


[1 2 3 4 5 6 7 8 9]
[4 5 8]


In [ ]:
#이거는 복습 잘해야함
#이것도 한번 더 풀어보자~

import numpy as np
#2차원 팬시 인덱싱
arr = np.arange(1,10).reshape(3,3)
print(arr)

#2차원은 2개 들어가잖아. 층에 대한 인덱스 하나, 호에 대한 인덱스 하나. 뭐 행에 대한 거 하나 열에 관한 거 하나라는 이야기임.
#print(arr[[1,2],[2,1]]) #아 이것도 똑같네. 앞에가 층이고 뒤에가 호고. [[층,호],[층,호]] 뭐 이런식이잖아. 몇층에 몇호, 몇층에 몇호.

#팬시인덱싱과 범위 인덱싱을 섞어서도 사용할 수 있음.
#print(arr[[1,2],:2])

#[1,2,3]
#[7,8,9] 이렇게 가져오려면 어떻게 해야할까?
#print(arr[[0,2],:]) #여기 층 부분 이렇게 되는 이유가 [0,2]이게 지금 arange()도 아니고 range()도 아니잖아? 심지어 범위도 아님. 그냥 0번 인덱스, 2번 인덱스임. np에서 arr[0][2] 이거 한거랑 a[0,2] 이거랑 같은 거 ㅇㅋ?
arr[ [0,2] ,: ]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
#2회차

#[1,2,3]
#[7,8,9] 이렇게 가져오려면 어떻게 해야할까?

arr = np.arange(1,10).reshape(3,3)

arr[ [0,2],: ]

#생각해야할 기본개념같은 게 파이썬에서 슬라이싱할 때는 늘 [,] 대괄호 안에서 슬라이싱 했다. 단지 대괄호 속에 리스트로 들어가는 것 뿐이야. 

array([[1, 2, 3],
       [7, 8, 9]])

불린 인덱싱

In [ ]:
#1차원
#불린 인덱싱은 True와 False 이거 두개로 되는 건데, 그 중에서 True 요소인 것만 가져오는 것임
arr = np.arange(1,10)
print(arr)
print(arr[arr > 5]) # ndarray에서 5보다 큰 거만 뽑아서 출력해보자. 원본에는 손 안대고. 지금 여기에 조건식 넣어준 거임.
print(arr[arr > 5])  #그래 이 부분. 이 부분이 잘 이해가 안돼.==> 원본에는 손 안대고 조건에 맞는 것만 출력해주는 거!!!!!
 
print( arr > 5 ) #조건식들. 이 조건식들을 통해 True False가 어떻게 바뀌는지 잘 확인해보자. 

#일부분만 갖고 오고 싶다면, 그 부분만 True로 바꿔주고 가져오면 되잖아? 

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#얘도 복습 열심히 해야겠다. 이해하려면. 갑자기 이렇게 빵 어려워져서 당황스러움.

name = np.array([ '홍길동','박철수', '이혜슈', '김영원','을지문덕' ])
name_score = np.array( [[60,60],[70,70],[80,80],[90,90],[100,100]] ) #name_score라는 2차원 ndarray 만들었음. 
#이 두개 ndarray가 지금 원소 인덱스 위치가 딱 맞잖아? 지금 약간 키값 대응되듯 된 거임.
print(name)
name_score

['홍길동' '박철수' '이혜슈' '김영원' '을지문덕']


array([[ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

In [ ]:
#name에서 홍길동만 가져오고 싶을 때. -> name에서 홍길동을 제외한 건 다 False로 출력하겠다.
name == '홍길동' #근데 이게 name의 원본 데이터를 건드리는 건 아님. 그냥 이째로 출력하면.. 아 이걸 조건식으로 걸고 출력해볼까?
#print(name[name == '홍길동']) #name == '홍길동' 이게 조건식일 때 이걸 만족하는 홍길동만 지금 출력해준 건데. 홍길동 빼고 다 false로 나오는 걸 따로 저장할 순 없을까?
print(name == '홍길동')
#print(player)

#name에서 홍길동 점수만 가져오고 싶을 때
name_score[ name == '홍길동' ]


[ True False False False False]


In [ ]:
#홍길동 2회차 ?????
##name에서 홍길동만 가져올 때
print(name[name == '홍길동'])

['홍길동']


#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

In [ ]:
#bmi 구하기 내가 푼 것 => 이게 numpy 스럽게 만들어준 것. 통째로 계산되는 거! 똑같은 크기면 각각 요소들끼리 계산이 된다!
#numpy를 쓰면 속도도 빠름 ㅋㅋ

data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",")  #구글 연동 먼저하고, 데이터 불러오기 한 것.
print(data)

height = data[0,:] / 100
weight = data[1,:]

bmi = weight / height **2
print(bmi)

#만약에 키에 대해 20 더하고 싶다면, data[0] + 20 이렇게 하면 됨. 이게 행렬에 대한 연산. 모든 요소가 동일한 연산이 수행됨. 아. 행렬에 더하기 하면 이렇잖아. 행렬 더하기 활용한 거네.
#키와 몸무게 크기가 같으니까(들어있는 차원과 요소 개수) 그러니까 그냥 통째로 연산 수행해도 상관 없네. 행렬이니까 통째로 연산 수행하는 게 가능한 거야.

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [ ]:
#bmi 구하기. 리스트 활용해서!

data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",")  #구글 연동 먼저하고, 데이터 불러오기 한 것.
print(data)

bmi = []
for i in range(0,10):  #요소 하나하나씩 불러오면서 할 때. 
  bmi.append(data[1,0] / ((data[0,0]**2) / 100))

bmi

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]


[0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312,
 0.2137153103563312]

### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

In [ ]:
#ndarray가 정렬하고 뭐 비슷하다고 봐도 됨.
#argsort()는 원본 행렬의 위치가 원래 어땠었다~ 라는 걸 알려주는 거임

org_array = np.array( [3,1,8,5] )

#sort()는 오름차순으로 바뀌고, 원본은 변경하지 않고 그대로 둠.
sort_array = np.sort(org_array)
print(org_array)
print(sort_array)

# array.sort()하면 자기 자신이 바뀌기 때문에 원본이 바뀜.
#org_array.sort()  #원본은 대부분 보존하려 하니까 이렇게 쓰지마. 원본은 바꾸지 않는 게 거의 좋음.

org_array[::-1] #내림차순과 똑같은 효과임
np.sort(org_array)[::-1]

[3 1 8 5]
[1 3 5 8]


array([8, 5, 3, 1])

In [ ]:
#2차원 정렬
array = np.array( [[8,12],
                   [7,1]] )

np.sort(array) #2차원같은 경우는 방향이 2방향이잖아. 행방향 열방향으로. 이 방향을 보통 '축'이라고 부름.

print(np.sort(array, axis=0))  #0방향은 행방향. 1방향은 열방향임.
print(np.sort(array, axis=1))  #0방향은 행방향. 1방향은 열방향임.


[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [ ]:
#argsort를 써보자.

org_array = np.array( [3,1,8,5] )
np.argsort(org_array) #원본 인덱스 위치를 정렬 시켜주는 것임. 원본에서의 위치 인덱스가 어디였는지 확인 가능. 원래대로였으면, 오름차순으로 정렬 상태였으면 위치가 어떻게 됐을지 보여주는 것.
                      #어디다 써먹냐 이거? 팬시 인덱싱으로 쓸 수 있음. 소팅 이전의 위치대로 값을 가져올 수 있으니까

array([1, 0, 3, 2])

In [ ]:
#argsort()의 활용
#소팅 된 위치를 가져올 수 있다~
#복습 때 여기 잘 이해해보자

name = np.array([ '홍길동','박철수', '이혜슈', '김영원','을지문덕' ])
name_score = np.array( [78, 95, 84, 98, 88] )

sort_index = np.argsort( name_score )   #sorting을 한다는 건 점수순대로 소팅하겠다는 거임. 소팅한 순서가 이름대로 들어가겠지. 그거대로 이름을 나열시키면?

sort_index = np.argsort( name_score )[::-1] #역순으로 한 것.  

print( sort_index )
print( name[sort_index] )

[3 1 4 2 0]
['김영원' '박철수' '을지문덕' '이혜슈' '홍길동']


### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ...
- 선형대수 연산 : 행렬 내적과 전치 행렬

In [ ]:
#행렬 일반 연산
array = np.array( [1,2,3] )
array + 100   #이게 되는 건 행렬 연산이니까 가능.

array + array #이것도 같은 위치끼리 더함. 왜냐? 행렬 연산이니까.

array * array #행렬은 곱셈이 2개임. 행렬곱과 그냥 요소들끼리 곱이 있음. 이건 그냥 요소들끼리의 곱임. 

array - array #같은 값에서 같은 값 빼면 다 0되지 ㅋㅋㅋ

array([0, 0, 0])

In [ ]:
array == 1 #이건 불린 연산. array == 1 이렇게 하면 자동으로 for문 돌아가짐. 자동으로 for문 돌아가면서 True인지 False인지 찾아주는 거임.
array == array #이건 다 True로 나온다.

array([ True, False, False])

In [ ]:
#특수한 행렬 곱. 행렬곱, 행렬의 내적.
#dot()
#행렬과 벡터의 곱이 dot()임. 
#1차원에서의 행렬 곱은 행벡터는 열벡터는 어짜피 방향은 하나. 차원은 하나임. 방향이 하나니까. 그냥 내적 구하듯 곱하면 된다. 그러면 하나가 나옴. 지금 14 이렇게.

np.dot(array, array) 

14

In [ ]:
#2차원에서의 곱. 행렬곱은 행렬의 내적이다. 정사각형으로 할 때랑 직사각형으로 할 때랑 다름. 내가 했던 방법은 정사각형으로 구하는 것이었다. 벡터 행렬곱 다시 보자.


a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[7,8],
              [9,10],
              [11,12]])

np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [ ]:
#전치 행렬  #그냥 가로 세로 축만 바뀌는 거임. 전치행렬 두번 바꾸면 그대로임.ㅋㅋ
#np.transpose()

np.transpose(a) #a의 행과 열의 위치를 교환해준다.
a.T   #이렇게 하면 바로 행과 열을 바꿔준다.
a.T.T #이렇게 하면 다시 바꾸니까 그대로됨~

### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

In [ ]:
array = np.arange(1,11)
array.sum()   #sum() 함수 쓰면 한번에 다 더해줌.
array.mean()  #mean() 평균 구하기


In [ ]:
array = np.array( [-1,-2,3,4,-5] )
#numpy에 있는 abs() 함수를 쓰면 전부 다 절댓값으로 바뀜. for문을 써서 하나씩 바꿔줄 필요가 없음.
np.abs(array)

#numpy는 진짜 개쩌넹. for문도 없어주고 numpy는 문서를 한번 열심히 들여다봐야겠다.

array([1, 2, 3, 4, 5])

##### Numpy 예제 04

영화평점 데이터 분석 ###이거만 완전히 이해하고 제대로 복습해도 되겠다.

In [ ]:
data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::', dtype=np.int64)      #txt는 csv나 엑셀에서 그런 것들 불러올 때 많이 쓰임
data



array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

##### 데이터 분석하기
```
print(data.ndim)
print(data.shape)
print(data.size)
```

In [ ]:
print(data.ndim)
print(data.shape) #층에 39만 1개, 호가 4개
print(data.size)  #총 개수는 12만 4개

2
(300001, 4)
1200004


##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

In [ ]:
#1. 평점 데이터만 추출
rating_all = data[:, 2]   # 층은 전체, 호는 범위 연산자를 사용한 게 아니니까 2번만 가져옴. 즉, 평점만 가져온다는 이야기

#rating_all.mean()

#추출해서 평균 구하기
np.mean( data[:,2] )

3.5613081289729034

##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

In [ ]:
#unique 함수. 중복없이 카운팅 해주는 것. 사용자가 1번 부터 몇번까지 있는지 확인 가능
user_id_all = np.unique( data[:,0] )
user_id_all.shape

(1779,)

In [ ]:
#1번 사용자의 데이터만 boolean index 추출
user_1 = data[ data[:,0] == 1 ]   #######중요#############  data 여기서 조건에 맞는 것만 추출해주는 거임!! data 원본에 영향을 주지 않고!


In [ ]:
#1번 사용자의 평점 평균 구하기
#1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
user_1 #user1에 대한 데이터임. 위에서 평균 구한 것과 똑같은 방향으로 구할 수 있음.

data[ data[:,0] == i ][:,2].mean()] #1번 사용자의 평점평균 구하기

np.mean( user_1[:,2] )

4.188679245283019

In [ ]:
#내가 푼 것!!!

#각 사용자별 평점 평균
score_mean = []

#user_id_all로 for문 돌리면 되잖아.

for i in user_id_all:
  score_mean.append( [i, data[ data[:, 0] == i ][:, 2].mean()] )

#평점은 구했는데 사용자 id정보가 누락되어있음. => 지금은 i로 id 정보 포함되어있음

print(score_mean)

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606], [11, 3.2773722627737225], [12, 3.8260869565217392], [13, 3.388888888888889], [14, 3.32], [15, 3.3233830845771144], [16, 3.0285714285714285], [17, 4.075829383886256], [18, 3.6491803278688524], [19, 3.5725490196078433], [20, 4.083333333333333], [21, 2.909090909090909], [22, 3.0673400673400675], [23, 3.3157894736842106], [24, 3.948529411764706], [25, 3.7411764705882353], [26, 2.96], [27, 4.171428571428572], [28, 3.7570093457943927], [29, 3.5833333333333335], [30, 3.488372093023256], [31, 3.73109243697479], [32, 3.625], [33, 3.498721227621483], [34, 3.8658536585365852], [35, 3.54040404040404], [36, 4.199430199430199], [37, 3.69811320754717], [38, 3.58], [39, 3.564516129032258], [40, 3.4479166666666665], [41, 3.48], [42, 3.74025974025974], [43, 4.12

##### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
- 리스트는 Boolean Indexing이 안되니 배열로 변환해야 인덱싱, 슬라이싱 가능

[   4.    5.    6. ... 1777. 1778. 1779.]


In [ ]:
### 영화 평점 구하기 ###
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
#print(data)

#데이터 분석해보기
#print(data.ndim) #2차원에
#print(data.shape) #층이 300001개, 호가 4개씩
#print(data.size) # 총 원소 개수가 12만 4개

#전체 평점 구하기
#1. 평점 데이터 추출
rating_all = data[:,2] #층은 다 추출하고, 호는 2번 위치 호만 쭈루룩 뽑아볼게~

#2. 평균 구하기 (mean)
rating_all_avg = np.mean(rating_all)
#print(rating_all_avg)

#각 사용자별 평점 평균 구하기
#참고) 중복된 성분을 제외한 array를 반환하는 np.unique(ndarray) 함수 존재
#unique 함수 써서 중복없이 카운팅. 사용자가 1번부터 몇번까지 있는지 확인 가능.
all_user_id = np.unique(data[:,0])
#print(all_user_id)

#1) 1번 사용자의 평균 평점 구하기

user1 = data[data[:,0] == 1]    #user1 사용자의 데이터만 boolean index 추출
#print(user1)

#1-1) 1번 사용자의 데이터에서 평점만 추출
#1-2) 평균 구하기
user1[:,2].mean() #바로 .mean(하면 됐네 ㅋㅋ)

#각 사용자별 평점 평균. for문 활용해서
score_mean = []

for i in all_user_id:
  score_mean.append( [i,data[data[:,0] == i][:,2].mean()] ) #리스트로 안묶으면 2개씩 append하는 것 같음.

print(score_mean)
#어쨌건 이거로 전체 인원들 평점 평균 구하기 성공

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606], [11, 3.2773722627737225], [12, 3.8260869565217392], [13, 3.388888888888889], [14, 3.32], [15, 3.3233830845771144], [16, 3.0285714285714285], [17, 4.075829383886256], [18, 3.6491803278688524], [19, 3.5725490196078433], [20, 4.083333333333333], [21, 2.909090909090909], [22, 3.0673400673400675], [23, 3.3157894736842106], [24, 3.948529411764706], [25, 3.7411764705882353], [26, 2.96], [27, 4.171428571428572], [28, 3.7570093457943927], [29, 3.5833333333333335], [30, 3.488372093023256], [31, 3.73109243697479], [32, 3.625], [33, 3.498721227621483], [34, 3.8658536585365852], [35, 3.54040404040404], [36, 4.199430199430199], [37, 3.69811320754717], [38, 3.58], [39, 3.564516129032258], [40, 3.4479166666666665], [41, 3.48], [42, 3.74025974025974], [43, 4.12

In [ ]:
### 영화 평점 구하기 ###
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
print(data)
#데이터 분석해보기
data.ndim
data.shape
data.size

#전체 평점 구하기
#1. 평점 데이터 추출
rating_all = data[:,2]
#2. 평균 구하기 (mean)
rating_all.mean() #이렇게 써도 되고
np.mean(rating_all) #이렇게 써도 되네.


#각 사용자별 평점 평균 구하기
#참고) 중복된 성분을 제외한 array를 반환하는 np.unique(ndarray) 함수 존재
#unique 함수 써서 중복없이 카운팅. 사용자가 1번부터 몇번까지 있는지 확인 가능.
all_user_id = np.unique(data[:,0])
all_user_id

#1) 1번 사용자의 평균 평점 구하기
user1 = data[data[:,0] == 1]
user1

#1-1) 1번 사용자의 데이터에서 평점만 추출
#1-2) 평균 구하기
user1_avg = user1[:,2].mean()
user1_avg

#각 사용자별 평점 평균. for문 활용해서
avg = []

#일단 나는. 반복문을 써서 avg.append 해줄 건데. 각 사용자 별로 할 거잖아? 각 사용자 이걸 i로 넣고 돌리면서 아까 1번 사용자 평점 평균 구하듯 하면 되지 않을까?
for i in all_user_id:
  avg.append([i, data[data[:,0] == i][:,2].mean()])

avg

In [ ]:
### 영화 평점 구하기 ###
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
print(data)
#데이터 분석해보기
data.ndim
data.shape
data.size


##전체 평점 구하기
##1. 평점 데이터 추출
data[:,2]

##2. 평균 구하기 (mean)
data[:,2].mean()


##각 사용자별 평점 평균 구하기
##참고) 중복된 성분을 제외한 array를 반환하는 np.unique(ndarray) 함수 존재
##unique 함수 써서 중복없이 카운팅. 사용자가 1번부터 몇번까지 있는지 확인 가능.
all_user_id = np.unique(data[:,0])
all_user_id

##1) 1번 사용자의 평균 평점 구하기
#난 불린으로 1번만 true 걸고 뽑아낼 거임
user1 = data[data[:,0] == 1]


##1-1) 1번 사용자의 데이터에서 평점만 추출
user1_star = user1[:,2]
user1_star
##1-2) 평균 구하기
user1_star_mean = user1_star.mean()
user1_star_mean

##각 사용자별 평점 평균. 
#난 이거 빈리스트 만들어서 넣어줄 거다? for문 돌려서 쭉쭉 넣을 거임.
user_star_mean = []

for i in all_user_id:
  user_star_mean.append([i, data[data[:,0] == i][:,2].mean()])

print(user_star_mean)

###4점 이상 사용자 출력하기
### 대박쓰다

##일단은 user_star_mean이 리스트잖아? 난 불린 인덱스를 쓰고 싶기 때문에, 난 이걸 ndarray로 바꿔줄 거야.
user_star_mean = np.array(user_star_mean, dtype='int64') ##어 이거 된다. array 안에서 dtype 지정해주기 되네!!!!
user_star_mean
##불린 인덱스로 만들기
#4점 이상인 것만 찾아서, 조건식 넣어줘. 4점 넘어가는 거만 뽑아내게.
user_star_mean[user_star_mean[:,1] >= 4][:,0] #그니까 이건 바로 아래 코드랑 동일한 거임. 봐봐~ 
a = user_star_mean[user_star_mean[:,1] >= 4] #a라는 변수에 할당했잖아? 할당하고 뒤에 한번 더 id 넣어주는 거랑 같은 거임. 이 줄 바로 위에 길게 쓴 거랑 이 줄 바로 아래에 a[] 이렇게 쓴 거랑 같다구~ 뭔지 이해했지?
a[:,0]
#와우 이걸 하네?

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     1779      2502         4 998699749]
 [     1779      3160         5 977032398]
 [     1779      3168         4 977033232]]
[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606], [11, 3.2773722627737225], [12, 3.8260869565217392], [13, 3.388888888888889], [14, 3.32], [15, 3.3233830845771144], [16, 3.0285714285714285], [17, 4.075829383886256], [18, 3.6491803278688524], [19, 3.5725490196078433], [20, 4.083333333333333], [21, 2.909090909090909], [22, 3.0673400673400675], [23, 3.3157894736842106], [24, 3.948529411764706], [25, 3.7411764705882353], [26, 2.96], [27, 4.171428571428572], [28, 3.7570093457943927], [29, 3.5833333333333335], [30, 3.488372093023256], [31, 

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [ ]:
### 영화 평점 구하기 ### 뭐 몇회차인지는 모르겠으나 복습할 때마다 풀고 있음
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
data
##데이터 분석해보기
data.ndim
data.shape
data.size

##전체 평점 구하기
##1. 평점 데이터 추출
data[:,2]

##2. 평균 구하기 (mean)
data[:,2].mean()


##각 사용자별 평점 평균 구하기
##1) 1번 사용자의 평균 평점 구하기
##1-1) 1번 사용자의 데이터에서 평점만 추출
#불린 쓸 건데,
user1 =  data[data[:,0] == 1]
user1[:,2]

##1-2) 평균 구하기
user1_mean = user1[:,2].mean()
user1_mean

##각 사용자별 평점 평균. 
##참고) 중복된 성분을 제외한 array를 반환하는 np.unique(ndarray) 함수 존재
##unique 함수 써서 중복없이 카운팅. 사용자가 1번부터 몇번까지 있는지 확인 가능.
all_user_id = np.unique( data[:,0] )
all_user_mean = []
#for문 써서 올유저 아이디에 있는 값을 하나씩 돌리면서 불린 쓰면 되겠다!
for i in all_user_id:
  all_user_mean.append([i, data[data[:,0] == i][:,2].mean()]) #append는 값 하나씩만 받는대~
all_user_mean

###4점 이상 사용자 출력하기
### 대박쓰다

##일단은 user_star_mean이 리스트잖아? 난 불린 인덱스를 쓰고 싶기 때문에, 난 이걸 ndarray로 바꿔줄 거야.
# 이렇게 형변환 할 때부터 데이터 타입을 지정해줄 순 있는데, 그렇게 안하고 이번엔 .astype()으로 한번 해볼게. nd_all_user_mean = np.array(all_user_mean, dtype='int')
nd_all_user_mean = np.array(nd_all_user_mean, dtype='float')
nd_all_user_mean = nd_all_user_mean.astype(int)
nd_all_user_mean
##불린 인덱스로 만들기
nd_all_user_mean[nd_all_user_mean[:,1] >= 4][:,0]

#이걸 또 해냅니다.

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [ ]:
### 영화 평점 구하기 ### 진짜 몇회차지 이거>>?? 아래로 내릴 수록 회차 올라가는 건데 넘파이는.
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

#data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
#data

##데이터 분석해보기
data.ndim
data.shape
data.size

##전체 평점 구하기
##1. 평점 데이터 추출
data[:,2] #이렇게 뽑는 이유 = [:][2] 전체층, 2호 이거랑 [:,2]랑 같음. 층 호

##2. 평균 구하기 (mean)
data[:,2].mean()


##각 사용자별 평점 평균 구하기
##1) 1번 사용자의 평균 평점 구하기
##1-1) 1번 사용자의 데이터에서 평점만 추출
#불린 쓸 건데,
data[data[:,0] == 1]

##1-2) 평균 구하기
data[data[:,0] == 1][:,2]

##각 사용자별 평점 평균. 
##참고) 중복된 성분을 제외한 array를 반환하는 np.unique(ndarray) 함수 존재
##unique 함수 써서 중복없이 카운팅. 사용자가 1번부터 몇번까지 있는지 확인 가능.
a_u_i = np.unique(data[:,0]) 
a_u_i_m = []

for i in a_u_i:
  a_u_i_m.append( [i, data[data[:,0] == i][:,2].mean()] )

a_u_i_m = np.array( a_u_i_m, dtype='int' )

###4점 이상 사용자 출력하기
### 대박쓰다

##일단은 user_star_mean이 리스트잖아? 난 불린 인덱스를 쓰고 싶기 때문에, 난 이걸 ndarray로 바꿔줄 거야.
# 이렇게 형변환 할 때부터 데이터 타입을 지정해줄 순 있는데, 그렇게 안하고 이번엔 .astype()으로 한번 해볼게. nd_all_user_mean = np.array(all_user_mean, dtype='int')
a_u_i_m[a_u_i_m[:,1] >= 4][:,0]

##불린 인덱스로 만들기

#이걸 또또 해냅니다. 

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [ ]:
### 영화 평점 구하기 ### 세보니까 이번이 7회차
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

#data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
#data

##데이터 분석해보기
##전체 평점 구하기
##1. 평점 데이터 추출
data[:,2]

##2. 평균 구하기 (mean)
data[:,2].mean()

##각 사용자별 평점 평균 구하기
##1) 1번 사용자의 평균 평점 구하기
##1-1) 1번 사용자의 데이터에서 평점만 추출

data[data[:,0] == 1][:,2]

##1-2) 평균 구하기
data[data[:,0] == 1][:,2].mean()


##각 사용자별 평점 평균. 

#일단 이거 난 for문 돌려서 빈 리스트에 다 넣을 건데, 유니크 함수를 쓰면 중복 없애주거든? 그거 중복 없애고 넣은 아이디로 반복문 돌려보자.
a_u_i = np.unique( data[:,0] )
a_u_i_m = []
for i in a_u_i:
  a_u_i_m.append( [i, data[data[:,0] == i][:,2].mean()] )

###4점 이상 사용자 출력하기
### 대박쓰다
#이것도 불린 쓸 것 같은데, 4점 이상만 뽑아서 사용자 출력하기로. 근데 일단 리스트를 ndarray로 바꿔야지.
da = np.array( a_u_i_m, dtype='int64' )
da[da[:,1] >= 4][:,0] 
#이걸 또또 해냅니다. 

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [ ]:
### 영화 평점 구하기 ### 세보니까 이번이 8회차
###이거 완전히 이해해서 안보고 아예 줄줄줄 쓸 수 있으면 복습 끝임.###

data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter='::',dtype=np.int64)
data

##데이터 분석해보기
##전체 평점 구하기
##1. 평점 데이터 추출
data[:,2]

##2. 평균 구하기 (mean)
data[:,2].mean()

##각 사용자별 평점 평균 구하기
##1) 1번 사용자의 평균 평점 구하기
data[data[:,0] == 1][:,2].mean()


##각 사용자별 평점 평균.
a_u_i = np.unique(data[:,0])
a_u_i_m = []

for i in a_u_i:
  a_u_i_m.append( [ i, data[data[:,0] == i][:,2].mean()  ] )
a_u_i_m

###4점 이상 사용자 출력하기
### 대박쓰다

a_u_i_m = np.array( a_u_i_m, dtype = 'int' )
a_u_i_m[a_u_i_m[:,1] >= 4][:,0]

#이젠 참 쉽다!

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [ ]:
#4점 이상 사용자 출력하기
### 대박쓰다

#일단은 avg가 리스트잖아? 난 불린 인덱스를 쓰고 싶기 때문에, 난 이걸 ndarray로 바꿔줄 거야.
avg_arr = np.array(avg)
#불린 인덱스로 만들기
avg_arr[avg_arr[:,1] >= 4][:,0].astype('int64') #파이썬은 자동으로 형변환하잖아. 실수형으로 자동 형변환해서 아까 이상하게 나온 거다.  .astype('int64')로 형태 지정해주면 정수로 쓸 수 있음!!!!


###### 질문

평점 4점이 넘는 사용자만 구하려면,
user_rate_avg의 결과 값을 리스트로 모은 후 ndarray 형식으로 바꾸는 방법밖에 없나요?

##### CSV 파일로 저장
- np.savetxt() 이용

In [ ]:
np.savetxt(drive_path + 'user_id_mean.csv', avg_arr, delimiter=', ', fmt='%3f') #%3f는 소수점 아래 3자리까지라고 포매팅한 거임.

## Numpy 요약

In [ ]:
import numpy as np